[tools]
ruby = "3.4"
bun = "1.3"

[tasks.dev]
# run = "bin/rails server"
run = "bin/dev"

[tasks.buildpush]
run = "docker buildx build --platform linux/amd64 -t \"registry.deploys.app/wiweksikkaram/app-rails:latest\" --push ."